[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"
  base = "."

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_TWILIO_ACCOUNT_SID = ""
  NEXT_PUBLIC_TWILIO_AUTH_TOKEN = ""
  NEXT_PUBLIC_TWILIO_PHONE_NUMBER = ""
  NEXT_PUBLIC_API_URL = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
