[build]
  command = "pip install -r requirements.txt && npm install && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11.7"
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_TWILIO_ACCOUNT_SID = ""
  NEXT_PUBLIC_TWILIO_AUTH_TOKEN = ""
  NEXT_PUBLIC_TWILIO_PHONE_NUMBER = ""
  NEXT_PUBLIC_API_URL = ""
  NPM_FLAGS = "--legacy-peer-deps"
  PIP_FLAGS = "--no-cache-dir"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
