import {
  Phone,
  Calendar,
  Activity,
  Settings,
  Users,
  BarChart,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Plus,
  Search,
  SortAsc,
  SortDesc,
  ArrowUpDown,
  Check,
  ChevronsLeft,
  ChevronsRight,
  MoreHorizontal,
  EyeOff,
  Trash,
  Copy,
  RotateCcw,
  Edit,
  UserCheck,
  UserX,
  Target,
  Filter,
  Mail,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = typeof LucideIcon

export const Icons = {
  phone: Phone,
  calendar: Calendar,
  activity: Activity,
  settings: Settings,
  users: Users,
  analytics: BarChart,
  logout: LogOut,
  menu: Menu,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  plus: Plus,
  search: Search,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  sort: ArrowUpDown,
  check: Check,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  more: MoreHorizontal,
  hidden: EyeOff,
  trash: Trash,
  copy: Copy,
  reset: RotateCcw,
  edit: Edit,
  userCheck: UserCheck,
  userX: UserX,
  target: Target,
  filter: Filter,
  mail: Mail,
}
